FROM tomcat:8.5.35-jre10
RUN ["apt-get", "update"]
RUN ["apt-get", "-y", "install", "vim"]
ADD Calendar.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD chmod +x /usr/local/tomcat/bin/catalina.sh
CMD ["catalina.sh", "run"]
